# These are all the cops that are enabled in the default configuration.
AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - "vendor/**/*"
    - "db/schema.rb"
    - "db/migrate/*"
    - "lib/templates/**/*"

Style/StringLiterals:
  Description: 'Checks if uses of quotes match the configured preference.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#consistent-string-literals'
  EnforcedStyle: single_quotes
  Enabled: true

Metrics/LineLength:
  Description: 'Limit lines to 120 characters.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#80-character-limits'
  Max: 120
  Enabled: true

Layout/TrailingBlankLines:
  Description: 'Checks trailing blank lines and final newline.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#newline-eof'
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

# Multi-line method chaining should be done with leading dots.
Layout/DotPosition:
  Enabled: true
  EnforcedStyle: trailing

Layout/EndAlignment:
  AutoCorrect: true

Style/FormatStringToken:
  Enabled: false

Style/AsciiComments:
  Description: 'Use only ascii symbols in comments.'
  StyleGuide: '#english-comments'
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Metrics/MethodLength:
  Max: 40

Metrics/ModuleLength:
  Max: 250

Metrics/ClassLength:
  Max: 250

Metrics/BlockLength:
  Max: 250

Metrics/AbcSize:
  # The ABC size is a calculated magnitude, so this number can be an Integer or
  # a Float.
  Max: 40

Rails/SkipsModelValidations:
  Blacklist:
    - decrement!
    - decrement_counter
    - increment!
    - increment_counter
    - toggle!
    - touch
    - update_attribute
    - update_column
    - update_columns
    - update_counters

Rails:
  Enabled: true
